#!/system/bin/sh

clear
log_file="/storage/emulated/0/fixgoogleanalytics.log"

echo "" > "$log_file"

googleanalytics='com.google.android.gms.analytics.AnalyticsJobService '\
'com.google.android.gms.analytics.CampaignTrackingService '\
'com.google.android.gms.measurement.AppMeasurementService '\
'com.google.android.gms.measurement.AppMeasurementJobService '\
'com.google.android.gms.analytics.AnalyticsReceiver '\
'com.google.android.gms.analytics.CampaignTrackingReceiver '\
'com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver '\
'com.google.android.gms.measurement.AppMeasurementReceiver '\
'com.google.android.gms.measurement.AppMeasurementContentProvider '\
'com.crashlytics.android.CrashlyticsInitProvider '\
'com.google.android.gms.ads.AdActivity '\
'com.google.firebase.iid.FirebaseInstanceIdService'

echo "==========================================================" | tee -a $log_file
echo "Setting targetted google anayltics on applications to: $1" | tee -a $log_file
echo ""
echo "Please wait as this will take some time to complete depending" | tee -a $log_file 
echo "on number of applications installed" | tee -a $log_file
echo ""
echo "$(pm list packages -3 | wc -l) packages installed" | tee -a $log_file
echo ""


packagecount=0
fixcount=0
failcount=0

# process list of applications
for apk in $(pm list packages -3 | sed 's/package://g' | sort); 
	do	
		(( packagecount++ ))
	    echo -ne "$packagecount packages processed \r"
		
		# for every application, disable the list of google analytics above
		for i in $googleanalytics
			do 
				# run actual command, and output successful state change or output not found if service is not found in apk
				output=$(pm "$1" "$apk/$i" 2>&1) && { echo "$output" >> "$log_file" ; fixcount=$((fixcount+1)); } || { echo "Component {"$apk/$i"} NOT FOUND" >> "$log_file"; failcount=$((failcount+1)); }
		done		
done

echo '==========================================================' | tee -a "$log_file"
echo "Analytics And Ad Receivers $1d: $fixcount" | tee -a "$log_file"
echo "Analytics And Ad Receivers NOT $1d/found: $failcount" | tee -a "$log_file"
echo '==========================================================' | tee -a "$log_file"



